language: scala
scala:
   - 2.11.8

script: "sbt ++$TRAVIS_SCALA_VERSION coverage test"
after_success:
   - "bash <(curl -s https://codecov.io/bash)"
   - "sbt ++$TRAVIS_SCALA_VERSION versioneye:updateProject"

jdk:
  - oraclejdk8

# Use container-based infrastructure
sudo: false

env:
  global:
    #VERSIONEYE_API_KEY=xxx
    secure: "e6idZd9HaBWn8YGwP3DGc5oe0K8Nz0ZF1jQBUM1QXkjA90LnSSTY1zCGaYNlCU6MSglbDJObQSG+LP6ZhIL5Eiau+ugA4frd97miEw1jgPzAXAiTLVZqux3FNKPpwe9oJVf82yqoa2Sk4UuR2hdcOOjL+chQRkrVFBKsBupUO4NYNYQX5hV9QSllxTKnKToIxzu+dRRGEPl5etA8G17XFVe3qE1x3bgEZKgh8woikFO8Orm84eXKEswCkotfMN51LqpHAFFTO3PryD05z7AwfRDTQOsBHkZXvigRgbfkHO82FUwot4hh8plyL9n3If3Mdd9OCMA6IFl0/UwWtQjTeqjGu1PvxRUx0mvUl1xsrN2tduxmpWbHCglpupwWIdnwwRA67Iz3TwFCLS8sQm96uogCNuz6fOV48izO9X4n0zbAHw5h5Iz9NPycPzRrXvNFEr84j6BywM3BQFFiSKsvByZi8CfBN/+zByp9g0vXKSmoViX8iftz1i6HrikSRFS6KIWUD8XxBmygt+N3uECcd0knrKTu4n9z8qWcleLJIZ2g2inXHaSCesCeauCK6PXCg39BkqY+1Li2wJpPlI++C9gT7icVxdtpocSw+JelXzo619BxRBPL4v/wfOTiZxpNhIRu63Jji6GRkke9wqpGVJjgkY727t6W6B6DIQkCBok="

cache:
  directories:
  - $HOME/.sbt/0.13/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache

before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

notifications:
  slack:
    rooms: dingsteam:RAMFhHHEJFRie1VmpxfhKnix
    on_success: always
    on_failure: always
    on_start: never
    on_pull_requests: false